name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  image_picker: ^1.1.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
