version: '3.8'

services:
  springboot-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - detector

  detector:
    build: ./people-detector-python
    ports:
      - "8000:8000"
